media:
  input: public/images/blog
  output: /images/blog
content:
  
  - name: posts
    label: Posts
    type: collection
    path: 'content/posts'
    fields:
      - name: title
        label: Title
        type: string
      - name: published
        label: Published
        type: boolean
        default: true
      - name: description
        label: Description
        type: string
        options: {maxlength: 160}
      - name: date
        label: Date
        type: date
      - name: author
        label: author
        type: object
        fields:
          - name: name
            label: First name
            type: string
          - name: avatar
            label: avatar
            type: image
      - name: image
        label: image
        type: image
      - name: body
        label: Body
        type: rich-text
  - name: site
    label: Site settings
    path: content/data/site.json
    type: file
    fields:
      - name: title
        label: Website title
        type: string
      - name: description
        label: Website description
        type: string
        description: Will be provused for any page with no description.
      - name: url
        label: Website URL
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
      - name: cover
        label: Preview image
        type: image
        description: Image used in the social preview on social networks (e.g. Facebook, Twitter...)
